esphome:
  name: esp-fan1

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "1Qpt7JptKZpkwmZFMjUPqCPQgRzAIJ3jt2Rc3FjeKPM="

ota:
#  password: "46d36ad2aba2496eb351da1ed480e219"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Fan1 Fallback Hotspot"
#    password: "0L9uX30nv4ZK"

captive_portal:


switch:
  - platform: gpio
    name: "fan01"
    pin: 23
  - platform: gpio
    name: "fan02"
    pin: 22    
  - platform: gpio
    name: "fan03"
    pin: 19
  - platform: gpio
    name: "fan04"
    pin: 18        
  - platform: gpio
    name: "fan05"
    pin: 17
  - platform: gpio
    name: "fan06"
    pin: 16        