esphome:
  name: esp-sw03

esp32:
  board: lolin_d32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5718eb8353b42e3d054c7f56a0d9ca6e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Sw03 Fallback Hotspot"
#    password: "aWt8PyPq4iO1"

captive_portal:

switch:
  - platform: gpio
    pin: GPIO13
    id: fan_relay1
    name: "Fan Relay #1"
    restore_mode : ALWAYS_OFF
    #on_turn_on:
    #  then:
    #  - switch.toggle: relay1
  - platform: gpio
    pin: GPIO14
    id: fan_relay2
    name: "Fan Relay #2"
    restore_mode : ALWAYS_OFF

  - platform: gpio
    pin: GPIO15
    id: fan_relay3
    name: "Fan Relay #3"
    restore_mode : ALWAYS_OFF
  
  - platform: gpio
    pin: GPIO16
    id: fan_relay4
    name: "Fan Relay #4"
    restore_mode : ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO17
    id: fan_relay5
    name: "Fan Relay #5"
    restore_mode : ALWAYS_OFF
    
