esphome:
  name: esp-pzem02

esp8266:
  board: esp12e

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:

ota:
  password: "2a8be79f70ca23ae55aed2300a4dd71f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Pzem02 Fallback Hotspot"


captive_portal:


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

modbus:
  send_wait_time: 500ms
  
sensor:
  - platform: pzemac
    id : guest_house_pzem
    current:
      name: "Guest House Current"
    voltage:
      name: "Guest House Voltage"
    energy:
      name: "Guest House Energy"
    power:
      name: "Guest House Power"
    frequency:
      name: "Guest House Frequency"
    power_factor:
      name: "Guest House Power Factor"
    update_interval: 10s
    address: 1

  - platform: pzemac
    id : guest_solar_pzem
    current:
      name: "Guest Solar Current"
    voltage:
      name: "Guest Solar Voltage"
    energy:
      name: "Guest Solar Energy"
    power:
      name: "Guest Solar Power"
    frequency:
      name: "Guest Solar Frequency"
    power_factor:
      name: "Guest Solar Power Factor"
    update_interval: 10s
    address: 2
