esphome:
  name: esp-wing-01
      
esp8266:
  board: d1_mini

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp-wing-01 Fallback Hotspot"

captive_portal:

light:
  - platform: status_led
    id: system_led
    pin: D4  

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: D5
    clock_pin: D7
    latch_pin: D6
   # oe_pin: D1
    sr_count: 2
  
number:
  - platform: template
    name: wing1 Inching Time
    optimistic: true
    id: inching_t
    entity_category: config
    unit_of_measurement: 's'
    min_value: 0
    max_value: 300
    step: 10
    initial_value: 300

switch:
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 15
    id: wing_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
    id: L1_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto


  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
    id: L1_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
    id: L2_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
    id: L2_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
    id: L3_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 5
    id: L3_sub

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 6
    id: R1_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 7
    id: R1_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 8
    id: R2_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 9
    id: R2_sub

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 10
    id: R3_main
    on_turn_on:
      if:
        condition:
          switch.is_off: wing_auto
        then:
          switch.turn_on: wing_auto
    on_turn_off:
      if:
        condition:
          and:
            - switch.is_off: L1_main
            - switch.is_off: L2_main
            - switch.is_off: L3_main
            - switch.is_off: R1_main
            - switch.is_off: R2_main
            - switch.is_off: R3_main
        then:
          switch.turn_off: wing_auto
              
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 11
    id: R3_sub

###############################
  - platform: template
    name: wing1_L1_up
    id: wing1_L1_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L1_down
      - delay: 0.2s
      - switch.turn_off: L1_sub
      - delay: 0.2s
      - switch.turn_on: L1_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L1_up 
    turn_off_action:
      - switch.turn_off: L1_main
      - delay: 0.1s
      - switch.turn_off: L1_sub
      
  - platform: template
    name: wing1_L1_down
    id: wing1_L1_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L1_up
      - delay: 0.2s      
      - switch.turn_on: L1_sub
      - delay: 0.2s
      - switch.turn_on: L1_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L1_down      
    turn_off_action:
      - switch.turn_off: L1_main
      - delay: 0.1s
      - switch.turn_off: L1_sub      
      
  - platform: template
    name: wing1_L2_up
    id: wing1_L2_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L2_down
      - delay: 0.2s
      - switch.turn_off: L2_sub
      - delay: 0.2s
      - switch.turn_on: L2_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L2_up      
    turn_off_action:
      - switch.turn_off: L2_main
      - delay: 0.1s
      - switch.turn_off: L2_sub
      
  - platform: template
    name: wing1_L2_down
    id: wing1_L2_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L2_up 
      - delay: 0.2s
      - switch.turn_on: L2_sub
      - delay: 0.2s
      - switch.turn_on: L2_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L2_down     
    turn_off_action:
      - switch.turn_off: L2_main
      - delay: 0.1s
      - switch.turn_off: L2_sub     
      
  - platform: template
    name: wing1_L3_up
    id: wing1_L3_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L3_down
      - delay: 0.2s
      - switch.turn_off: L3_sub
      - delay: 0.2s
      - switch.turn_on: L3_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L3_up      
    turn_off_action:
      - switch.turn_off: L3_main
      - delay: 0.1s
      - switch.turn_off: L3_sub
      
  - platform: template
    name: wing1_L3_down
    id: wing1_L3_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L3_up
      - delay: 0.2s
      - switch.turn_on: L3_sub
      - delay: 0.2s
      - switch.turn_on: L3_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_L3_down      
    turn_off_action:
      - switch.turn_off: L3_main
      - delay: 0.1s
      - switch.turn_off: L3_sub     
############################

  - platform: template
    name: wing1_R1_up
    id: wing1_R1_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R1_down
      - delay: 0.2s
      - switch.turn_off: R1_sub
      - delay: 0.2s
      - switch.turn_on: R1_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R1_up      
    turn_off_action:
      - switch.turn_off: R1_main
      - delay: 0.1s
      - switch.turn_off: R1_sub
      
  - platform: template
    name: wing1_R1_down
    id: wing1_R1_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R1_up
      - delay: 0.2s      
      - switch.turn_on: R1_sub
      - delay: 0.2s
      - switch.turn_on: R1_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R1_down            
    turn_off_action:
      - switch.turn_off: R1_main
      - delay: 0.1s
      - switch.turn_off: R1_sub      
      
  - platform: template
    name: wing1_R2_up
    id: wing1_R2_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R2_down
      - delay: 0.2s
      - switch.turn_off: R2_sub
      - delay: 0.2s
      - switch.turn_on: R2_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R2_up            
    turn_off_action:
      - switch.turn_off: R2_main
      - delay: 0.1s
      - switch.turn_off: R2_sub
      
  - platform: template
    name: wing1_R2_down
    id: wing1_R2_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R2_up 
      - delay: 0.2s
      - switch.turn_on: R2_sub
      - delay: 0.2s
      - switch.turn_on: R2_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R2_down            
    turn_off_action:
      - switch.turn_off: R2_main
      - delay: 0.1s
      - switch.turn_off: R2_sub     
      
  - platform: template
    name: wing1_R3_up
    id: wing1_R3_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R3_down
      - delay: 0.2s
      - switch.turn_off: R3_sub
      - delay: 0.2s
      - switch.turn_on: R3_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R3_up            
    turn_off_action:
      - switch.turn_off: R3_main
      - delay: 0.1s
      - switch.turn_off: R3_sub
      
  - platform: template
    name: wing1_R3_down
    id: wing1_R3_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R3_up
      - delay: 0.2s
      - switch.turn_on: R3_sub
      - delay: 0.2s
      - switch.turn_on: R3_main
      - delay: !lambda "return id(inching_t).state * 1000;"
      - switch.turn_off: wing1_R3_down            
    turn_off_action:
      - switch.turn_off: R3_main
      - delay: 0.1s
      - switch.turn_off: R3_sub  

# ########################################      
# cover:
#   - platform: time_based
#     name: cover_L1
#     id: cover_L1
#     open_action:
#       - switch.turn_on: wing1_L1_up
#     open_duration: 51000ms
#     close_action:
#       - switch.turn_on: wing1_L1_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_L1_up
#       - switch.turn_off: wing1_L1_down

#   - platform: time_based
#     name: cover_L2
#     id: cover_L2
#     open_action:
#       - switch.turn_on: wing1_L2_up
#     open_duration: 51770ms
#     close_action:
#       - switch.turn_on: wing1_L2_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_L2_up
#       - switch.turn_off: wing1_L2_down      

#   - platform: time_based
#     name: cover_L3
#     id: cover_L3
#     open_action:
#       - switch.turn_on: wing1_L3_up
#     open_duration: 51770ms
#     close_action:
#       - switch.turn_on: wing1_L3_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_L3_up
#       - switch.turn_off: wing1_L3_down 

#   - platform: time_based
#     name: cover_R1
#     id: cover_R1
#     open_action:
#       - switch.turn_on: wing1_R1_up
#     open_duration: 51770ms
#     close_action:
#       - switch.turn_on: wing1_R1_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_R1_up
#       - switch.turn_off: wing1_R1_down

#   - platform: time_based
#     name: cover_R2
#     id: cover_R2
#     open_action:
#       - switch.turn_on: wing1_R2_up
#     open_duration: 51770ms
#     close_action:
#       - switch.turn_on: wing1_R2_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_R2_up
#       - switch.turn_off: wing1_R2_down      

#   - platform: time_based
#     name: cover_R3
#     id: cover_R3
#     open_action:
#       - switch.turn_on: wing1_R3_up
#     open_duration: 51770ms
#     close_action:
#       - switch.turn_on: wing1_R3_down
#     close_duration: 51200ms
#     stop_action:
#       - switch.turn_off: wing1_R3_up
#       - switch.turn_off: wing1_R3_down                