esphome:
  name: esp-dist02

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Dist02 Fallback Hotspot"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
#    name: "Ultrasonic Sensor"
    id: u_dist
    update_interval: 10s

  - platform: template
    name: Ultrasonic Sensor
    lambda: |-
      return (1.4 - id(u_dist).state) * 100.0;
    unit_of_measurement: cm

  - platform: template
    name: Turbidity Sensor
    lambda: |-
      return id(turbidity_mv).state;
    filters:
      - calibrate_linear:
        - 0.37  -> 0.0
        - 0.02 -> 100.0
    unit_of_measurement: '%'    
    
  - platform: adc
    id: turbidity_mv
    pin: A0    
    update_interval: never
    accuracy_decimals: 3
    filters:
      - multiply: 3.3
      - filter_out: 0.37
      - quantile:
          window_size: 100
          send_every: 100
          quantile: .5

switch:
  - platform: gpio
    pin: D5
    id: ntc_vcc
    
interval:
  - interval: 10s
    then:
      - switch.turn_on: ntc_vcc
      - delay: 0.1s
      - repeat:
          count: 100
          then:
            - component.update: turbidity_mv
            - delay: 0.01s
      - switch.turn_off: ntc_vcc        
    
    