esphome:
  name: esp-ntc04

esp8266:
  board: d1_mini

logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "C9iI1GsHuYELcIviZouAjWecM71ZTi5wLvQtoc3VMh0="

ota:
#  password: "85b779cebf77623c26e86e453990cebd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Ntc04 Fallback Hotspot"
#    password: "8QOeQzQxMmgg"

captive_portal:

sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      - 6430Ohm -> 39.9°C
      - 11380Ohm -> 24.5°C
      - 16221Ohm -> 15.5°C
    name: NTC Temp4
#    filters:
#      - median:
#          window_size: 3
#         send_every: 1

      
  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 9.1kOhm
#    name: NTC R4
    
  - platform: adc
    id: source_sensor
    pin: A0    
    update_interval: never
    accuracy_decimals: 3
    filters:
      - multiply: 3.3
      - quantile:
          window_size: 100
          send_every: 100
          quantile: .5
          
switch:
  - platform: gpio
    pin: D0
    id: ntc_vcc
    
interval:
  - interval: 10s
    then:
      - switch.turn_on: ntc_vcc
      - delay: 0.1s
      - repeat:
          count: 100
          then:
            - component.update: source_sensor
            - delay: 0.01s
      - switch.turn_off: ntc_vcc    
    