esphome:
  name: esp-soil

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Soil Fallback Hotspot"


captive_portal:

deep_sleep:
  run_duration: 20s
  sleep_duration: 10min
  
i2c:
  sda: 16
  scl: 17
  
sensor:
  - platform: dht
    pin: GPIO22
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s    

  - platform: adc
    pin: GPIO32
    name: "Soil Moisture"
    update_interval: 5s
    
#    raw: true
    attenuation: auto
    device_class: "humidity"
    state_class: "measurement"
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
        - 2.68 -> 0.0
        - 1.24 -> 100.0

  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
#    current:
#      name: "INA226 Current"
#    power:
#      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
#    shunt_voltage:
#      name: "INA226 Shunt Voltage"
    max_current: 3.2A
    update_interval: 5s
