esphome:
  name: esp-test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fZ9FPyDquvBnUG9awdZEvDrbk7IcwpFwUYW+A5JiUjE="

ota:
  password: "4aaf7634f37242fa2b335bb27549d6fd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Test Fallback Hotspot"
    password: "J1EbFatkRa4e"

captive_portal:
    