esphome:
  name: esp-rfid

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Rfid Fallback Hotspot"

captive_portal:

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output

rtttl:
  output: pwm_output


spi:
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6

rc522_spi:
  cs_pin: D8
#  reset_pin: D3
  on_tag:
    then:
      - if:
          condition:
            binary_sensor.is_on: RFID
          then:
            rtttl.play: 'scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b'
      - if:
          condition:
            binary_sensor.is_off: RFID
          then:
            rtttl.play: 'two short:d=4,o=5,b=100:16e6,16e6'

binary_sensor:
  - platform: rc522
    uid: 63-D5-30-1D
    id: RFID     