esphome:
  name: esp-sw10
      
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:
  level: ERROR
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Sw10 Fallback Hotspot"

captive_portal:

      
switch:
  - platform: gpio
    pin: GPIO22
    id: relay1
    name: "Power1 ON"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay1

  - platform: gpio
    pin: GPIO21
    id: relay2
    name: "Power1 OFF"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay2

  - platform: gpio
    pin: GPIO19
    id: relay3
    name: "Power2 ON"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay3

  - platform: gpio
    pin: GPIO18
    id: relay4
    name: "Power2 OFF"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay4
      
  - platform: gpio
    pin: GPIO5
    id: relay5
    name: "Power3 ON"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay5

  - platform: gpio
    pin: GPIO17
    id: relay6
    name: "Power3 OFF"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay6      
      
  - platform: gpio
    pin: GPIO4
    id: relay7
    name: "Power4 ON"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay7

  - platform: gpio
    pin: GPIO2
    id: relay8
    name: "Power4 OFF"
    restore_mode : ALWAYS_OFF
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay8     
      
sensor:
  - platform: adc
    pin: GPIO36
    attenuation: 11db
    id: adc1
    update_interval: 1s

  - platform: adc
    pin: GPIO39
    attenuation: 11db
    id: adc2
    update_interval: 1s
    
  - platform: adc
    pin: GPIO34
    attenuation: 11db
    id: adc3
    update_interval: 1s

  - platform: adc
    pin: GPIO35
    attenuation: 11db
    id: adc4
    update_interval: 1s
    
binary_sensor:
  - platform: template
    name: "Moter1"
    lambda: |-
      if (id(adc1).state > 2.6) {
        return true;
      } else {
        return false;
      }   

  - platform: template
    name: "Moter2"
    lambda: |-
      if (id(adc2).state > 2.6) {
        return true;
      } else {
        return false;
      }  
      
  - platform: template
    name: "Moter3"
    lambda: |-
      if (id(adc3).state > 2.6) {
        return true;
      } else {
        return false;
      }  
      
  - platform: template
    name: "Moter4"
    lambda: |-
      if (id(adc4).state > 2.6) {
        return true;
      } else {
        return false;
      }        