esphome:
  name: esp-sonoff02

esp8266:
  board: esp8285

wifi:
  ssid: "ssfarm2G"
#  password: !secret wifi_password
  ap:
    ssid: "Esp-Sonoff01 Fallback Hotspot"

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

captive_portal:
