esphome:
  name: esp-disp
  platform: ESP32
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
#  password: "0aba24aa3216ab31b5e4df624317903d"

wifi:
  ssid: "dddddd"
  password: "asdf1234"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Disp Fallback Hotspot"
#    password: "uLDsrIXxWfo2"

captive_portal:

time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    #current:
    #  name: "INA226 Current"
    #power:
    #  name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
      id: bt_volt
    #shunt_voltage:
    #  name: "INA226 Shunt Voltage"
    max_current: 3.2A
    update_interval: 10s
    
  - platform: dht
    pin: GPIO27
    temperature:
      name: "BUS Temperature"
      id: bt_temp
    humidity:
      name: "BUS Humidity"
    update_interval: 10s
    
i2c:
  sda: D2
  scl: D1


font:
  - file: "fonts/arial.ttf"
    id: my_font
    size: 20
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(my_font), "%.1f V", id(bt_volt).state);
      it.printf(0, 24, id(my_font), "%.1f C", id(bt_temp).state);
#      it.strftime(0, 0, id(my_font), "%H:%M", id(esptime).now());
#      it.printf(0, 24, id(my_font), "Volt: %.1f V", id(bt_volt).state);      