esphome:
  name: esp-ntc05

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "C9iI1GsHuYELcIviZouAjWecM71ZTi5wLvQtoc3VMh0="

ota:
#  password: "85b779cebf77623c26e86e453990cebd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Ntc05 Fallback Hotspot"
#    password: "8QOeQzQxMmgg"

captive_portal:

sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3435
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: NTC Temperature
    filters:
      - sliding_window_moving_average:
          window_size: 7
          send_every: 5
      - lambda: |-
          const uint16_t DO_Table[41] = {
            14460, 14220, 13820, 13440, 13090, 12740, 12420, 12110, 11810, 11530,
            11260, 11010, 10770, 10530, 10300, 10080, 9860, 9660, 9460, 9270,
            9080, 8900, 8730, 8570, 8410, 8250, 8110, 7960, 7820, 7690,
            7560, 7430, 7300, 7180, 7070, 6950, 6840, 6730, 6630, 6530, 6410};
          uint16_t V_saturation = 1570 + (uint32_t)35 * 26 - (uint32_t)26 * 35;
          return (700 * DO_Table[26] / V_saturation);
      
  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 8.93kOhm
    name: Resistance Sensor
    
  - platform: adc
    id: source_sensor
    pin: GPIO36 
    attenuation: auto
    update_interval: never
    filters:
      - quantile:
          window_size: 10
          send_every: 1
          quantile: .5 

switch:
  - platform: gpio
    pin: GPIO32
    id: ntc_vcc

  - platform: restart
    name: "Restart"
    
interval:
  - interval: 4s
    then:
      - switch.turn_on: ntc_vcc
      - delay: 0.2s
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc    
    
    