esphome:
  name: esp-sw05

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
#  password: "fb530dd00a4b61fd3f414d4920a6069f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Sw05 Fallback Hotspot"
#    password: "DscEFdoJwIt3"

captive_portal:


button:
  - platform: template
    name: "Power ON"
    on_press:
      then:
        - switch.turn_on: relay1

  - platform: template
    name: "Power OFF"
    on_press:
      then:
        - switch.turn_on: relay2

        
switch:
  - platform: gpio
    id: relay1
    pin: D1   
    disabled_by_default : true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay1
      
  - platform: gpio
    id: relay2
    pin: D2  
    disabled_by_default : true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: relay2    