esphome:
  name: esp-sonoffpow01

esp8266:
  board: esp8285

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Sonoffpow01 Fallback Hotspot"

captive_portal:



uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "Sonoff Pow Current"
    voltage:
      name: "Sonoff Pow Voltage"
    power:
      name: "Sonoff Pow Power"
    energy:
      name: "Sonoff Pow Energy"
      
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes          