esphome:
  name: esp-disp02

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
#  password: "79e5e403bedabdfcc90672fd2e742bf5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Disp02 Fallback Hotspot"
#    password: "800ogSh9e1Pp"

captive_portal:


sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    #current:
    #  name: "INA226 Current"
    #power:
    #  name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
      id: bt_volt
    #shunt_voltage:
    #  name: "INA226 Shunt Voltage"
    max_current: 3.2A
    update_interval: 10s
    
    
i2c:
  sda: TX
  scl: RX    