esphome:
  name: esp-sw01

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Sw01 Fallback Hotspot"

captive_portal:


switch:
  - platform: gpio
    pin: GPIO12
    id: relay1
    name: "Relay #1"
    interlock: [relay2]
    restore_mode : ALWAYS_OFF
    #on_turn_on:
    #  then:
    #  - switch.toggle: relay1
  - platform: gpio
    pin: GPIO13
    id: relay2
    name: "Relay #2"
    interlock: [relay1]
    restore_mode : ALWAYS_OFF

  - platform: gpio
    pin: GPIO14
    id: relay3
    name: "Relay #3"
    interlock: [relay4]
    restore_mode : ALWAYS_OFF
  
  - platform: gpio
    pin: GPIO15
    id: relay4
    name: "Relay #4"
    interlock: [relay3]
    restore_mode : ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO18
    id: relay5
    name: "Relay #5"
    interlock: [relay6]
    restore_mode : ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO19
    id: relay6
    name: "Relay #6"
    interlock: [relay5]
    restore_mode : ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO21
    id: relay7
    name: "Relay #7"
    interlock: [relay8]
    restore_mode : ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO22
    id: relay8
    name: "Relay #8"
    interlock: [relay7]
    restore_mode : ALWAYS_OFF
    
binary_sensor:
  - platform: gpio
    filters:
      - invert:
    name: "Relay Switch1"
    pin: 
      number: GPIO23
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay1
    on_release:
      then:
        - switch.turn_off: relay1
  
  
  - platform: gpio
    filters:
      - invert:
    name: "Relay Switch2"
    pin: 
      number: GPIO25
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay2
    on_release:
      then:
        - switch.turn_off: relay2
        
        
  - platform: gpio
    filters:
      - invert:
    name: "Relay Switch3"
    pin: 
      number: GPIO26
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay3
    on_release:
      then:
        - switch.turn_off: relay3
  
            
  - platform: gpio
    filters:
      - invert:    
    name: "Relay Switch4"
    pin: 
      number: GPIO27
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay4
    on_release:
      then:
        - switch.turn_off: relay4
  
            
  - platform: gpio
    filters:
      - invert:
    name: "Relay Switch5"
    pin: 
      number: GPIO32
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay5
    on_release:
      then:
        - switch.turn_off: relay5
  
            
  - platform: gpio
    filters:
      - invert:
    name: "Relay Switch6"
    pin: 
      number: GPIO33
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay6
    on_release:
      then:
        - switch.turn_off: relay6
  
            
  - platform: gpio
    filters:
      - invert:    
    name: "Relay Switch7"
    pin: 
      number: GPIO2
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay7
    on_release:
      then:
        - switch.turn_off: relay7
  
          
  - platform: gpio
    filters:
      - invert:  
    name: "Relay Switch8"
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true    
    on_press:
      then:
        - switch.turn_on: relay8
    on_release:
      then:
        - switch.turn_off: relay8
  
          
        