esphome:
  name: "esp-wing1"
      
esp8266:
  board: d1_mini

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp-wing1 Fallback Hotspot"

captive_portal:

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: D5
    clock_pin: D7
    latch_pin: D6
   # oe_pin: D1
    sr_count: 2
  
switch:

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 7
      inverted: true
    name: wing1_auto

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: true
    id: wing1_L1_main

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
      inverted: true
    id: wing1_L1_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
      inverted: true
    id: wing1_L2_main

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
      inverted: true
    id: wing1_L2_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
      inverted: true
    id: wing1_L3_main

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 5
      inverted: true
    id: wing1_L3_sub
   
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 6
      inverted: true
    id: relay0

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 15
      inverted: true
    id: wing1_R1_main

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 14
      inverted: true
    id: wing1_R1_sub
  
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 13
      inverted: true
    id: wing1_R2_main

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 12
      inverted: true
    id: wing1_R2_sub

  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 11
      inverted: true
    id: wing1_R3_main
    
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 10
      inverted: true
    id: wing1_R3_sub
   
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 9
      inverted: true
    id: relay1
    
  - platform: gpio
    pin:
      sn74hc595: sn74hc595_hub
      number: 8
      inverted: true
    id: relay2

###############################

  - platform: template
    name: wing1_L1_up
    id: wing1_L1_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L1_down
      - delay: 0.2s
      - switch.turn_off: wing1_L1_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L1_main
    turn_off_action:
      - switch.turn_off: wing1_L1_main
      - delay: 0.1s
      - switch.turn_off: wing1_L1_sub
      
  - platform: template
    name: wing1_L1_down
    id: wing1_L1_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L1_up
      - delay: 0.2s      
      - switch.turn_on: wing1_L1_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L1_main
    turn_off_action:
      - switch.turn_off: wing1_L1_main
      - delay: 0.1s
      - switch.turn_off: wing1_L1_sub      
      
  - platform: template
    name: wing1_L2_up
    id: wing1_L2_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L2_down
      - delay: 0.2s
      - switch.turn_off: wing1_L2_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L2_main
    turn_off_action:
      - switch.turn_off: wing1_L2_main
      - delay: 0.1s
      - switch.turn_off: wing1_L2_sub
      
  - platform: template
    name: wing1_L2_down
    id: wing1_L2_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L2_up 
      - delay: 0.2s
      - switch.turn_on: wing1_L2_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L2_main
    turn_off_action:
      - switch.turn_off: wing1_L2_main
      - delay: 0.1s
      - switch.turn_off: wing1_L2_sub     
      
  - platform: template
    name: wing1_L3_up
    id: wing1_L3_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L3_down
      - delay: 0.2s
      - switch.turn_off: wing1_L3_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L3_main
    turn_off_action:
      - switch.turn_off: wing1_L3_main
      - delay: 0.1s
      - switch.turn_off: wing1_L3_sub
      
  - platform: template
    name: wing1_L3_down
    id: wing1_L3_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_L3_up
      - delay: 0.2s
      - switch.turn_on: wing1_L3_sub
      - delay: 0.2s
      - switch.turn_on: wing1_L3_main
    turn_off_action:
      - switch.turn_off: wing1_L3_main
      - delay: 0.1s
      - switch.turn_off: wing1_L3_sub     
############################

  - platform: template
    name: wing1_R1_up
    id: wing1_R1_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R1_down
      - delay: 0.2s
      - switch.turn_off: wing1_R1_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R1_main
    turn_off_action:
      - switch.turn_off: wing1_R1_main
      - delay: 0.1s
      - switch.turn_off: wing1_R1_sub
      
  - platform: template
    name: wing1_R1_down
    id: wing1_R1_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R1_up
      - delay: 0.2s      
      - switch.turn_on: wing1_R1_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R1_main
    turn_off_action:
      - switch.turn_off: wing1_R1_main
      - delay: 0.1s
      - switch.turn_off: wing1_R1_sub      
      
  - platform: template
    name: wing1_R2_up
    id: wing1_R2_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R2_down
      - delay: 0.2s
      - switch.turn_off: wing1_R2_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R2_main
    turn_off_action:
      - switch.turn_off: wing1_R2_main
      - delay: 0.1s
      - switch.turn_off: wing1_R2_sub
      
  - platform: template
    name: wing1_R2_down
    id: wing1_R2_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R2_up 
      - delay: 0.2s
      - switch.turn_on: wing1_R2_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R2_main
    turn_off_action:
      - switch.turn_off: wing1_R2_main
      - delay: 0.1s
      - switch.turn_off: wing1_R2_sub     
      
  - platform: template
    name: wing1_R3_up
    id: wing1_R3_up
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R3_down
      - delay: 0.2s
      - switch.turn_off: wing1_R3_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R3_main
    turn_off_action:
      - switch.turn_off: wing1_R3_main
      - delay: 0.1s
      - switch.turn_off: wing1_R3_sub
      
  - platform: template
    name: wing1_R3_down
    id: wing1_R3_down
    optimistic : true
    turn_on_action:
      - switch.turn_off: wing1_R3_up
      - delay: 0.2s
      - switch.turn_on: wing1_R3_sub
      - delay: 0.2s
      - switch.turn_on: wing1_R3_main
    turn_off_action:
      - switch.turn_off: wing1_R3_main
      - delay: 0.1s
      - switch.turn_off: wing1_R3_sub  

########################################      
cover:
  - platform: time_based
    name: cover_L1
    id: cover_L1
    open_action:
      - switch.turn_on: wing1_L1_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_L1_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_L1_up
      - switch.turn_off: wing1_L1_down

  - platform: time_based
    name: cover_L2
    id: cover_L2
    open_action:
      - switch.turn_on: wing1_L2_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_L2_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_L2_up
      - switch.turn_off: wing1_L2_down      

  - platform: time_based
    name: cover_L3
    id: cover_L3
    open_action:
      - switch.turn_on: wing1_L3_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_L3_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_L3_up
      - switch.turn_off: wing1_L3_down 

  - platform: time_based
    name: cover_R1
    id: cover_R1
    open_action:
      - switch.turn_on: wing1_R1_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_R1_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_R1_up
      - switch.turn_off: wing1_R1_down

  - platform: time_based
    name: cover_R2
    id: cover_R2
    open_action:
      - switch.turn_on: wing1_R2_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_R2_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_R2_up
      - switch.turn_off: wing1_R2_down      

  - platform: time_based
    name: cover_R3
    id: cover_R3
    open_action:
      - switch.turn_on: wing1_R3_up
    open_duration: 51770ms
    close_action:
      - switch.turn_on: wing1_R3_down
    close_duration: 51200ms
    stop_action:
      - switch.turn_off: wing1_R3_up
      - switch.turn_off: wing1_R3_down                